request:
  url: https://example.com

runner:
  requests: 10
  concurrency: 2

tests:
  - name: minimum response time
    field: ResponseTimes.Min
    predicate: GT
    target: 80ms
  - name: maximum response time
    field: ResponseTimes.Max
    predicate: LTE
    target: 120ms
  - name: 100% availability
    field: RequestFailureCount
    predicate: EQ
    target: 0
