#!/bin/bash

cmddir="./cmd/server"
bindir="./bin/server"
output="${bindir:?}/server"

clearBinDirectory() {
    rm -rf "${bindir:?}/*"
}

buildExecutable() {
    go build -o "${output}" "${cmddir}"
}

printCompletionMessage() {
    echo -e "\033[1;32m✔︎\033[0m Build complete: ${output}"
}

main() {
    clearBinDirectory &&
        buildExecutable &&
        printCompletionMessage
}
main
