#!/bin/bash

platforms="darwin/amd64 darwin/arm64 linux/386 linux/amd64 windows/386 windows/amd64"

# clear bin directory
rm -rf ./bin/*

i=0
for platform in ${platforms}; do
    ((i++))

    split=(${platform//// }) # split platform by sep "/"
    goos="${split[0]}"
    goarch="${split[1]}"
    output="benchttp_${goos}_${goarch}" # e.g. benchttp_darwin_amd64

    # add .exe to windows binaries
    [[ "$goos" == "windows" ]] && output="$output.exe"

    output="./bin/$output"

    # build binary
    GOOS="$goos" GOARCH="$goarch" go build -tags prod -o "$output" ./cmd/benchttp

    echo "[$i/6] $output"
done

echo -e "\033[1;32m✔︎\033[0m Build complete!"
