name: Lint & Test & Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Install coverage tool
        run: go get github.com/ory/go-acc

      # Check #1: Lint
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.2

      # Check #2: Test & generate coverage report
      - name: Test & coverage
        run: make test-cov

      # Check #3: Build binaries
      - name: Build
        run: make build

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
